---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true

---

```{r}
library(tidyverse)
library(dplyr)
library(plotly)
library(p8105.datasets)
```
#
# Loading and cleaning data
#
```{r}
data("rest_inspec") 

rest_inspec2 =
  rest_inspec %>%
  select(boro, cuisine_description, dba, zipcode, violation_code, violation_description, grade, grade_date, critical_flag, score) %>%
mutate(zipcode = as.character(zipcode)) %>%
filter(!is.na(grade),!is.na(violation_description), !is.na(score)) %>%
filter(boro == "STATEN ISLAND", 
       !grade == "Not Yet Graded", 
       !grade == "P", 
       !grade == "Z")  

```
#
# Making Plotly Plots
#
```{r}
#Number of restaurants per grade
rest_inspec2 %>% 
  count(grade) %>% 
  mutate(grade = fct_reorder(grade, n)) %>% 
  plot_ly(x = ~grade , y = ~n, color = ~grade, type = "bar", colors = "viridis")


#ZIPCODE VS CUISINE 
rest_inspec2 %>% 
plot_ly(
    x = ~zipcode, y = ~cuisine_description, 
    type = "scatter", text = ~dba,
    mode = "markers",
    color = ~grade, alpha = 0.5)


#GRADE VS SCORE 
rest_inspec2 %>% 
  plot_ly(x = ~grade, y = ~score, color = ~grade, type = "box", colors = "viridis")


#ZIPCODE VS SCORE
rest_inspec2 %>% 
  plot_ly(x = ~zipcode, y = ~score, color = ~grade, type = "scatter",
          text = ~dba, mode = "markers", colors = "viridis")

```


